### ISSUE TITLE
rospy_message_converter: i'm lazy...can't you figure out the message_type? why do i have to do it?

### ISSUE THREAD

**Issue by mirzashah** [uos/rospy_message_converter#1]
In json_mesage_converter.py, I have to pass the message_type. That type is in the json isn't it? i think binney's code has to load the json and actually figure out the type and then call this function. can i get a version without the message_type. then i don't have to even think about what's going on in the json -- that's between you and argenteam. does that make sense?

**Comment by nyxaria** [comment]
@baalexander do you know how I can convert a string to a rosmsg type?
I have the string equivalent in the form "sensor_msgs.JointState"

What I need to do with this is create a publisher with this type
ie self.pub = rospy.Publisher(topic,
                                   string_to_type("sensor_msgs.JointState"),
                                   queue_size=10)

Thanks!
