### ISSUE TITLE
Release into Lunar + Melodic

### ISSUE THREAD

**Issue by mintar** [uos/rospy_message_converter#21]
Could you do a binary release into lunar and melodic? I've just tried it, and it compiles fine; also, all tests pass. So this should just be a matter of running bloom, no changes to the source code required.

**Comment by mintar** [comment]
Is this repo still maintained?

**Comment by veimox** [comment]
+1. Compiles and passes the test, just bloom needed

**Comment by mintar** [comment]
Ping...

**Comment by 130s** [comment]
+1
This blocks releases of e.g. Turtlebot into Melodic https://github.com/turtlebot/turtlebot/issues/272

**Comment by mintar** [comment]
It also blocks the release of mir_robot.

**Comment by jonbinney** [comment]
Pinging @baalexander - i don't think you use this package much anymore; would it make sense to give someone else push access to the source and release repos so they can bloom this for melodic?

**Comment by mintar** [comment]
I've taken over maintainership of this repo, merged all outstanding pull requests and fixed a couple of things. I've just done a new release it indigo and kinetic, as well as made the initial release into lunar and melodic:

* https://github.com/ros/rosdistro/pull/19974
* https://github.com/ros/rosdistro/pull/19975

Thanks @baalexander for your trust and for creating this nice package!
