### ISSUE TITLE
Installation fails with pip3

### ISSUE THREAD

**Issue by argenos** [uos/rospy_message_converter#27]
To reproduce this,  `rospkg` and `catkin-pkg` also need to be installed to work with python3, e.g. using pip3:

```
$ pip3 install rospy-message-converter
Collecting rospy-message-converter
  Using cached https://files.pythonhosted.org/packages/c3/7d/5e153b0d7dea31faa4a12505ff04f26dce77716f97d963af2e165ac12984/rospy_message_converter-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1zv7ys8z/rospy-message-converter/setup.py", line 8, in <module>
        package_dir={'' : 'src'},
      File "/usr/local/lib/python3.5/dist-packages/catkin_pkg/python_setup.py", line 74, in generate_distutils_setup
        package = parse_package(package_xml_path)
      File "/usr/local/lib/python3.5/dist-packages/catkin_pkg/package.py", line 513, in parse_package
        xml, filename = _get_package_xml(path)
      File "/usr/local/lib/python3.5/dist-packages/catkin_pkg/package.py", line 489, in _get_package_xml
        raise IOError('Path "%s" is neither a directory containing a "%s" file nor a file' % (path, PACKAGE_MANIFEST_FILENAME))
    OSError: Path "." is neither a directory containing a "package.xml" file nor a file
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1zv7ys8z/rospy-message-converter/

```

**Comment by mintar** [comment]
I'm currently on vacation, but I'll look into this in about two weeks. Thanks for the issue!

**Comment by argenos** [comment]
No problem! Not sure if this is an option, but we solved it in https://github.com/ropod-project/rospy_message_converter/pull/1 by using a `pyproject.toml` file. This also helped us install the dependencies in the right order when in a `requirements.txt` file, otherwise it would fail because it couldn't find `catkin_pkg` (which was also listed in that file).

**Comment by mintar** [comment]
The pip library was made by @cjds (see #14 and #25), so any questions about that should go to him.

It's not quite easy to set up Python3 with ROS at the moment, so I'm not sure what the proper fix for this would be. Pull requests welcome.

**Comment by nyxaria** [comment]
is there any progress on this?

**Comment by mintar** [comment]
Installation via pip or pip3 is unsupported. Please ask @cjds for any questions, since he's the one who uploaded the package to pip.

You should either build from source or use the prepackaged binaries, e.g. `sudo apt install ros-melodic-rospy-message-converter`.

**Comment by cjds** [comment]
Sorry that's my bad for not noticing the first "@". I'll take a look at it right now and let you know. @mintar with noetic coming out soon it's becoming easier to do python3 things with ROS

**Comment by cjds** [comment]
So this fails because my release of this library is 2 years old currently. The master version of this library does work and a re-release will fix it. I will try to get that done and update when I have it

**Comment by nyxaria** [comment]
Thank you @cjds :)

**Comment by cjds** [comment]
FYI update on this so far is I'm trying to recover the account that pushed the code up (unfortunately lost my recovery method). In the meantime, one workaround is a git clone and running `setup.py` manually from the top of this repo. I'll update you when I recover the account and have it released

**Comment by cjds** [comment]
https://pypi.org/project/rospy-message-converter/ has released a new version and now should work
