### ISSUE TITLE
Support for custom messages

### ISSUE THREAD

**Issue by nyxaria** [uos/rospy_message_converter#32]
Hi, first of all thank you for your wonderful work!

I wanted to ask if you support messages from packages like sensor_msgs, like JointState?

If not, how would I go about adding support for it?

Further, for completely custom messages, would this be the same?

Thank you very much!

**Comment by mintar** [comment]
Yes, rospy_message_converter supports all ROS messages that are built in your catkin workspace, including custom messages. In short: If `rosmsg show sensor_msgs/JointState` works in your terminal, it also works in rospy_message_converter.
