### ISSUE TITLE
Are uint8[] arrays converted to strings?

### ISSUE THREAD

**Issue by Otacon5555** [uos/rospy_message_converter#45]
It looks like so, I'm experiencing this issue:

a custom ROS msg has a field like

`uint8[8]  intensities`

and after

`json_str = json_message_converter.convert_ros_message_to_json(data)`

I see it is turned into a string (printing it with `rospy.loginfo(json_str)`).

Is it a bug or a feature?
Is it possible to force it to not consider it as a string?

Thank you.

**Comment by Otacon5555** [comment]
I believe it is a feature, as described in [issue #15 ](https://github.com/uos/rospy_message_converter/pull/15#issue-118557845)

Problem is, my desidered behaviour is the one that was considered a bug.

My workaround is removing from [line 260 of message_converter.py](https://github.com/uos/rospy_message_converter/blob/31c7d27051d845ff6611d8b085e13186349e410c/src/rospy_message_converter/message_converter.py#L260)

the condition `field_type.startswith('uint8[') or` , so that line becomes just `return field_type.startswith('char[')`

I understand that this would reopen aforementioned issue #15 - maybe `convert_ros_message_to_json` function could take an optional parameter to request the desired behaviour?

Thanks.

**Comment by mintar** [comment]
You are correct, it's not a bug, it's the desired behavior in most cases. It's also in line with what `rospy` does: If you receive a message with a `uint8[*]` field, rospy will treat it as a `str`. But I understand that's not *always* the desired behavior.

> maybe convert_ros_message_to_json function could take an optional parameter to request the desired behaviour?

I think I would be okay with such a parameter; let's call it `binary_array_as_str` or something. The default should be `True` to preserve the existing behavior. Unfortunately, since `_is_ros_binary_type` is nested so deep within the function calls, it means that flag has to passed down through all intermediate function calls until `_is_ros_binary_type` is finally called.

By the way, I first thought the opposite direction (`convert_dictionary_to_ros_message`) would also need some adjustments, but it turns out it can already handle lists of int. I've just added a test that verifies this:

https://github.com/uos/rospy_message_converter/blob/c980ac3080b32ff0e3c4294b248214103b5259cf/test/test_message_converter.py#L276-L286

> the condition field_type.startswith('uint8[') or , so that line becomes just return field_type.startswith('char[')

Note that `char` is just an ancient, deprecated alias for `uint8`, so both should be handled the same. In other words, the whole `_is_ros_binary_type` check should be skipped. That way, it'll be handled by the `_is_field_type_a_primitive_array` case.

If you could provide these changes as a pull request (with accompanying tests, see `test_ros_message_with_3uint8_array` for a start), I'd be glad to review it.

**Comment by Otacon5555** [comment]
Thank you.

I'll try to do this fix.

In the meantime I see you added some more tests, but I'm getting the following errors on a couple of them:

```
[Testcase: test_dictionary_with_3uint8_array_str] ... ERROR!
ERROR: a bytes-like object is required, not 'str'
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "test_message_converter.py", line 271, in test_dictionary_with_3uint8_array_str
    dictionary = {'data': standard_b64encode(expected_message.data)}
  File "/media/sf_ADAS/adas/3rdparty/ROS/venv/lib/python3.6/base64.py", line 95, in standard_b64encode                                                                                                            
    return b64encode(s)                                                                                                                                                                                           
  File "/media/sf_ADAS/adas/3rdparty/ROS/venv/lib/python3.6/base64.py", line 58, in b64encode                                                                                                                     
    encoded = binascii.b2a_base64(s, newline=False)                                                                                                                                                               
--------------------------------------------------------------------------------    


[Testcase: test_dictionary_with_uint8_array_str] ... ERROR!
ERROR: a bytes-like object is required, not 'str'
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "test_message_converter.py", line 250, in test_dictionary_with_uint8_array_str
    dictionary = {'data': standard_b64encode(expected_message.data)}
  File "/media/sf_ADAS/adas/3rdparty/ROS/venv/lib/python3.6/base64.py", line 95, in standard_b64encode
    return b64encode(s)
  File "/media/sf_ADAS/adas/3rdparty/ROS/venv/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
--------------------------------------------------------------------------------
```

**Comment by mintar** [comment]
I just fixed that: #46

**Comment by Otacon5555** [comment]
Thank you very much, but I'm sorry to say that I'm still gettin a (new) error:

```
[Testcase: test_dictionary_with_uint8_array_bytes_unencoded] ... FAILURE!
FAILURE: 'Invalid base64-encoded string: number of da[51 chars]of 4' != 'Incorrect padding'
- Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
+ Incorrect padding

  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "test_message_converter.py", line 306, in test_dictionary_with_uint8_array_bytes_unencoded
    context.exception.args[0])
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
--------------------------------------------------------------------------------
```

Next week I'll try to find the time to do the fix I proposed.

**Comment by mintar** [comment]
Ok, I've fixed that too. I tested on python2.7 and 3.8, but I didn't expect that 3.6 behaves differently... oh well.

**Comment by Otacon5555** [comment]
Thank you very much for the quick fix!

I've done the fix we discussed on a local branch: how can I submit it to you? I can't push the branch.

Thank you.

**Comment by mintar** [comment]
Please [open a pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

**Comment by Otacon5555** [comment]
I see that the test I added is passing only on noetic and failing on both kinetic and melodic, but I actually have melodic (with python 3.6) and the test was passing. As they say, "it works on my machine"...!

**Comment by mintar** [comment]
Let's move the discussion over to the Pull Request!
