### ISSUE TITLE
time as float

### ISSUE THREAD

**Issue by cosama** [uos/rospy_message_converter#53]
Right now ros time objects will be converted to a dictionary of the form `{'secs': sec_value, 'nsecs': nsecs_value}`. In my group we usually convert ros time directly to a float with the `to_sec()` function.

It would be cool if this could be supported here as well, maybe by adding a flag `time_as_float` or `time_to_sec`. I am happy to submit a merge request if you think this would be a nice feature to have.

**Comment by mintar** [comment]
Sorry for not getting back to you earlier. I prefer not to add this feature for the following reason: Converting from `secs` + `nsecs` to `float` loses precision, and if you convert back you will get a different result in most cases. The error will be small (on the order of 100 nanoseconds), but it will mess things up if you use a ExactTime synchronizer for example. For this reason, I'd prefer not to encourage the practise of converting time to float.

You can test this yourself:

```python
from rospy import Time

NUM_MSGS = 10000
l = []
t = Time(1636795445)    # Nov 13, 2021

for i in range(NUM_MSGS):
    t.nsecs = i
    if Time.from_sec(t.to_sec()) != t:
        l.append(i)

print("percentage of mismatches: ", len(l) / NUM_MSGS * 100)
```
