### ISSUE TITLE
ROS message type "std_msgs/String" has no field named "StrSys"

### ISSUE THREAD

**Issue by jingtong-liu** [uos/rospy_message_converter#55]
ROS message type "std_msgs/String" has no field named "StrSys"
But I can't find "StrSys" on the Internet

**Comment by mintar** [comment]
You're probably trying to convert a dictionary that has the key `StrSys` into a ROS message of type `std_msgs/String`. As the error message already says, this will not work. Your dictionary should only have the field `data`:

http://docs.ros.org/en/noetic/api/std_msgs/html/msg/String.html
